
artifacts_root: artifacts 

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/gbiamgaurav/github_datasets/raw/main/RTA-Dataset.zip
  local_data_file: artifacts/data_ingestion/RTA_data.zip
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/RTA Dataset.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_resampled.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: rta_model.joblib
